WITH DF AS(
select
	
    RBPC.TESOURARIA,
    RBPC.PRODUTO,
    RBPC.CODIGO,
    RBPC.MITRA_FINANCEIRO_ATIVO

from rel_book_precos_consolidado RBPC
inner join REL_APURACAO_FORMS RAF on
	RBPC.COD_REL_APURACAO_FORM = RAF.COD_REL_APURACAO_FORM
inner join REL_APURACAO RA on
	RAF.COD_REL_APURACAO = RA.CODIGO
where RA.CODIGO = (
        select max(RA.CODIGO)
        from REL_APURACAO RA
        where upper(RA.NOME) like upper('[RECON] FUNDAÇÃO%')
        and RA.data_final = '17/08/26'
    )
),   
 DI AS(
select
	
    RBPC.TESOURARIA,
    RBPC.PRODUTO,
    RBPC.CODIGO,
    RBPC.MITRA_FINANCEIRO_ATIVO

from rel_book_precos_consolidado RBPC
inner join REL_APURACAO_FORMS RAF on
	RBPC.COD_REL_APURACAO_FORM = RAF.COD_REL_APURACAO_FORM
inner join REL_APURACAO RA on
	RAF.COD_REL_APURACAO = RA.CODIGO
where RA.CODIGO = (
        select max(RA.CODIGO)
        from REL_APURACAO RA
        where upper(RA.NOME) like upper('[RECON] FUNDAÇÃO CERES%')
        and RA.data_final = '14/08/26'
    ))
SELECT 
DF.TESOURARIA,
DF.PRODUTO,
DF.CODIGO,
DI.MITRA_FINANCEIRO_ATIVO AS FIN_DI,
DF.MITRA_FINANCEIRO_ATIVO as FIN_DF,
DF.MITRA_FINANCEIRO_ATIVO - DI.MITRA_FINANCEIRO_ATIVO AS DIFERENCA,
(DF.MITRA_FINANCEIRO_ATIVO - DI.MITRA_FINANCEIRO_ATIVO) / ABS(DI.MITRA_FINANCEIRO_ATIVO) AS DIFF_PORCENTAGEM

FROM DF
INNER JOIN DI
ON DF.CODIGO = DI.CODIGO
ORDER BY ABS(DF.MITRA_FINANCEIRO_ATIVO - DI.MITRA_FINANCEIRO_ATIVO) DESC 