WITH ranked_rentabilidade_n3 AS (
    -- CONSULTA 1: Rentabilidades (Nível 3)
    SELECT 
        TO_CHAR(ra.DATA_INICIAL, 'DD/MM/YYYY') AS DATA_INICIAL,
        RAF.DATA_COTACAO,
        RME.TESOURARIA,
        RME.GRUPO,
        RME.CARTEIRA,
        RME.RENT_COTA_INICIO_MOEDA_NVAG/100 AS INICIO,
        RME.RENT_COTA_MTD_MOEDA_NVAG/100 AS MTD,
        RME.RENT_COTA_YTD_MOEDA_NVAG/100 AS YTD,
        RME.RENT_COTA_DIDF_MOEDA_NVAG/100 AS DIDF,
        RME.RENT_COTA_12M_MOEDA_NVAG/100 AS MESES12,
        RME.COTA_NIVEL_AGREGACAO_DI/100 AS DI,
        RME.COTA_NIVEL_AGREGACAO_DF/100 AS DF,
        RME.REFERENCIA_BENCHMARK,
        RA.NOME,
        ROW_NUMBER() OVER (
            PARTITION BY TRUNC(RAF.DATA_COTACAO), RME.TESOURARIA, RME.GRUPO, RME.CARTEIRA
            ORDER BY RAF.COD_REL_APURACAO_FORM DESC
        ) AS rn
    FROM rel_multi_estrategia_cota_nvag RME
    INNER JOIN REL_APURACAO_FORMS RAF ON
        RME.COD_REL_APURACAO_FORM = RAF.COD_REL_APURACAO_FORM
    INNER JOIN REL_APURACAO RA ON
        RAF.COD_REL_APURACAO = RA.CODIGO
    WHERE RME.NIVEL_AGREGACAO = 'Rentabilidade Cota Nível Agregação 3' 
    AND RA.NOME LIKE '[RESULTADO] FUNDAÇÃO CERES DIARIO OFICIAL#%'
),
ranked_posicao_n3 AS (
    -- CONSULTA 2: Posição DF (Nível 3)
    SELECT
        RAF.DATA_COTACAO,
        RME.TESOURARIA,
        RME.GRUPO,
        RME.CARTEIRA,
        RME.POSICAO_DF,
        ROW_NUMBER() OVER(                            
            PARTITION BY TRUNC(RAF.DATA_COTACAO), RME.TESOURARIA, RME.GRUPO, RME.CARTEIRA
            ORDER BY RAF.COD_REL_APURACAO_FORM DESC     
        ) AS rn                                         
    FROM REL_MULTI_ESTRATEGIA RME
    INNER JOIN REL_APURACAO_FORMS RAF ON
        RME.COD_REL_APURACAO_FORM = RAF.COD_REL_APURACAO_FORM
    INNER JOIN REL_APURACAO RA ON
        RAF.COD_REL_APURACAO = RA.CODIGO
    WHERE RME.NIVEL_AGREGACAO = 'Sintético Nível 3' 
    AND RA.NOME LIKE '[RESULTADO] FUNDAÇÃO CERES DIARIO OFICIAL#%'
),
ranked_rentabilidade_n2 AS (
    -- CONSULTA 3: Rentabilidades (Nível 2) APENAS CERES TOTAL
    SELECT 
        TO_CHAR(ra.DATA_INICIAL, 'DD/MM/YYYY') AS DATA_INICIAL,
        RAF.DATA_COTACAO,
        RME.TESOURARIA,
        RME.GRUPO,
        RME.RENT_COTA_INICIO_MOEDA_NVAG/100 AS INICIO,
        RME.RENT_COTA_MTD_MOEDA_NVAG/100 AS MTD,
        RME.RENT_COTA_YTD_MOEDA_NVAG/100 AS YTD,
        RME.RENT_COTA_DIDF_MOEDA_NVAG/100 AS DIDF,
        RME.RENT_COTA_12M_MOEDA_NVAG/100 AS MESES12,
        RME.COTA_NIVEL_AGREGACAO_DI/100 AS DI,
        RME.COTA_NIVEL_AGREGACAO_DF/100 AS DF,
        RME.REFERENCIA_BENCHMARK,
        RA.NOME,
        ROW_NUMBER() OVER (
            PARTITION BY TRUNC(RAF.DATA_COTACAO), RME.TESOURARIA, RME.GRUPO
            ORDER BY RAF.COD_REL_APURACAO_FORM DESC
        ) AS rn
    FROM rel_multi_estrategia_cota_nvag RME
    INNER JOIN REL_APURACAO_FORMS RAF ON
        RME.COD_REL_APURACAO_FORM = RAF.COD_REL_APURACAO_FORM
    INNER JOIN REL_APURACAO RA ON
        RAF.COD_REL_APURACAO = RA.CODIGO
    WHERE RME.NIVEL_AGREGACAO = 'Rentabilidade Cota Nível Agregação 2' 
    AND RA.NOME LIKE '[RESULTADO] FUNDAÇÃO CERES DIARIO OFICIAL#%'
    AND RME.TESOURARIA = '[CERES TOTAL]' 
),
ranked_posicao_n2 AS (
    -- CONSULTA 4: Posição DF (Nível 2) APENAS CERES TOTAL
    SELECT
        RAF.DATA_COTACAO,
        RME.TESOURARIA,
        RME.GRUPO,
        RME.POSICAO_DF,
        ROW_NUMBER() OVER(                            
            PARTITION BY TRUNC(RAF.DATA_COTACAO), RME.TESOURARIA, RME.GRUPO
            ORDER BY RAF.COD_REL_APURACAO_FORM DESC     
        ) AS rn                                         
    FROM REL_MULTI_ESTRATEGIA RME
    INNER JOIN REL_APURACAO_FORMS RAF ON
        RME.COD_REL_APURACAO_FORM = RAF.COD_REL_APURACAO_FORM
    INNER JOIN REL_APURACAO RA ON
        RAF.COD_REL_APURACAO = RA.CODIGO
    WHERE RME.NIVEL_AGREGACAO = 'Sintético Nível 2' 
    AND RA.NOME LIKE '[RESULTADO] FUNDAÇÃO CERES DIARIO OFICIAL#%'
    AND RME.TESOURARIA = '[CERES TOTAL]' 
)

-- SELECT FINAL: UNE AS DUAS CONSULTAS (Sem NOME e Sem CARTEIRA no resultado)
SELECT 
    R1.DATA_INICIAL,
    R1.DATA_COTACAO,
    R1.TESOURARIA,
    R1.GRUPO,
    R1.INICIO,
    R1.MTD,
    R1.YTD,
    R1.DIDF,
    R1.MESES12,
    R1.DI,
    R1.DF,
    R1.REFERENCIA_BENCHMARK,
    R2.POSICAO_DF 
FROM ranked_rentabilidade_n3 R1
LEFT JOIN ranked_posicao_n3 R2 ON
    TRUNC(R1.DATA_COTACAO) = TRUNC(R2.DATA_COTACAO)
    AND R1.TESOURARIA = R2.TESOURARIA
    AND R1.CARTEIRA = R2.CARTEIRA
    AND R1.GRUPO = R2.GRUPO  
WHERE R1.rn = 1
AND (R2.rn = 1 OR R2.rn IS NULL)
AND R1.TESOURARIA <> '[CERES TOTAL]' 
AND (
    (R1.GRUPO = 'Operações com Participantes' AND R1.CARTEIRA LIKE '%Emprestimos%')
    OR (R1.GRUPO = 'Operações com Participantes' AND R1.CARTEIRA LIKE '%(%%)%')
    OR (R1.GRUPO = 'Imobiliário' AND R1.CARTEIRA LIKE '%Imoveis%')
    OR (R1.GRUPO = 'Imobiliário' AND R1.CARTEIRA LIKE '%(%%)%')
    OR (R1.GRUPO NOT IN ('Operações com Participantes', 'Imobiliário'))
)

UNION ALL

-- ADICIONA A CONSULTA DE NÍVEL 2 (CERES TOTAL)
SELECT 
    R3.DATA_INICIAL,
    R3.DATA_COTACAO,
    R3.TESOURARIA,
    R3.GRUPO,
    R3.INICIO,
    R3.MTD,
    R3.YTD,
    R3.DIDF,
    R3.MESES12,
    R3.DI,
    R3.DF,
    R3.REFERENCIA_BENCHMARK,
    R4.POSICAO_DF 
FROM ranked_rentabilidade_n2 R3
LEFT JOIN ranked_posicao_n2 R4 ON
    TRUNC(R3.DATA_COTACAO) = TRUNC(R4.DATA_COTACAO)
    AND R3.TESOURARIA = R4.TESOURARIA
    AND R3.GRUPO = R4.GRUPO  
WHERE R3.rn = 1
AND (R4.rn = 1 OR R4.rn IS NULL)

-- ORDENAÇÃO DE TUDO NO FINAL
ORDER BY DATA_COTACAO DESC, TESOURARIA;